import { Order } from '../../constants';

export const mockData: Order[] = [
  {
    rowId: 1,
    orderId: '1',
    orderDate: '2023-01-01',
    shipDate: '2023-01-02',
    shipMode: 'Standard',
    customerId: '1',
    customerName: 'Test Customer',
    segment: 'Consumer',
    country: 'USA',
    city: 'Test City',
    state: 'CA',
    postalCode: 12345,
    region: 'West',
    productId: '1',
    category: 'Electronics',
    subCategory: 'Phones',
    productName: 'Test Phone',
    sales: 100,
    quantity: 1,
    discount: 0,
    profit: 10,
  },
  {
    rowId: 2,
    orderId: '2',
    orderDate: '2023-01-01',
    shipDate: '2023-01-02',
    shipMode: 'Standard',
    customerId: '2',
    customerName: 'Test Customer 2',
    segment: 'Consumer',
    country: 'USA',
    city: 'Test City 2',
    state: 'NY',
    postalCode: 12345,
    region: 'East',
    productId: '1',
    category: 'Electronics',
    subCategory: 'Phones',
    productName: 'Test Phone',
    sales: 200,
    quantity: 1,
    discount: 0,
    profit: 20,
  },
  {
    rowId: 3,
    orderId: '3',
    orderDate: '2023-01-01',
    shipDate: '2023-01-02',
    shipMode: 'Standard',
    customerId: '3',
    customerName: 'Test Customer 3',
    segment: 'Consumer',
    country: 'USA',
    city: 'Test City 3',
    state: 'CA',
    postalCode: 12345,
    region: 'West',
    productId: '2',
    category: 'Electronics',
    subCategory: 'Laptops',
    productName: 'Test Laptop',
    sales: 300,
    quantity: 1,
    discount: 0,
    profit: 30,
  },
  {
    rowId: 4,
    orderId: '4',
    orderDate: '2023-01-01',
    shipDate: '2023-01-02',
    shipMode: 'Standard',
    customerId: '4',
    customerName: 'Test Customer 4',
    segment: 'Consumer',
    country: 'USA',
    city: 'Test City 4',
    state: 'NY',
    postalCode: 12345,
    region: 'East',
    productId: '3',
    category: 'Clothing',
    subCategory: 'Shirts',
    productName: 'Test Shirt',
    sales: 150,
    quantity: 1,
    discount: 0,
    profit: 15,
  },
]; 