export enum OrderFields {
  RowId = 'rowId',
  OrderId = 'orderId',
  OrderDate = 'orderDate',
  ShipDate = 'shipDate',
  ShipMode = 'shipMode',
  CustomerId = 'customerId',
  CustomerName = 'customerName',
  Segment = 'segment',
  Country = 'country',
  City = 'city',
  State = 'state',
  PostalCode = 'postalCode',
  Region = 'region',
  ProductId = 'productId',
  Category = 'category',
  SubCategory = 'subCategory',
  ProductName = 'productName',
  Sales = 'sales',
  Quantity = 'quantity',
  Discount = 'discount',
  Profit = 'profit',
}
